/**
 * Removes Astro's and Vite's build caches.
 *
 * These hold compiled copies of the modules `astro.config.mjs` imports — the
 * rehype directive plugins among them — plus the rendered content collection.
 * Editing one of those files does not always invalidate the cached copy, so a
 * build can keep emitting the previous markup with no sign that anything is
 * wrong. Reach for this when a change to a plugin or to the Astro config seems
 * to have no effect.
 *
 * Everything here is gitignored and regenerated by the next build, so removing
 * it is always safe — it only costs a slower first build.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const targets = ["node_modules/.astro", "node_modules/.vite", ".astro"];

let removed = 0;
for (const target of targets) {
	const full = path.join(root, target);
	if (!fs.existsSync(full)) {
		console.log(`  skip     ${target} (absent)`);
		continue;
	}
	fs.rmSync(full, { recursive: true, force: true });
	removed += 1;
	console.log(`  removed  ${target}`);
}

console.log(`cache cleaned (${removed}/${targets.length} present)`);
